// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type PostingValueType int32

const (
	PostingValueTypeDEFAULT  PostingValueType = 0
	PostingValueTypeBINARY   PostingValueType = 1
	PostingValueTypeINT      PostingValueType = 2
	PostingValueTypeFLOAT    PostingValueType = 3
	PostingValueTypeBOOL     PostingValueType = 4
	PostingValueTypeDATETIME PostingValueType = 5
	PostingValueTypeGEO      PostingValueType = 6
	PostingValueTypeUID      PostingValueType = 7
	PostingValueTypePASSWORD PostingValueType = 8
	PostingValueTypeSTRING   PostingValueType = 9
	PostingValueTypeOBJECT   PostingValueType = 10
)

var EnumNamesPostingValueType = map[PostingValueType]string{
	PostingValueTypeDEFAULT:  "DEFAULT",
	PostingValueTypeBINARY:   "BINARY",
	PostingValueTypeINT:      "INT",
	PostingValueTypeFLOAT:    "FLOAT",
	PostingValueTypeBOOL:     "BOOL",
	PostingValueTypeDATETIME: "DATETIME",
	PostingValueTypeGEO:      "GEO",
	PostingValueTypeUID:      "UID",
	PostingValueTypePASSWORD: "PASSWORD",
	PostingValueTypeSTRING:   "STRING",
	PostingValueTypeOBJECT:   "OBJECT",
}

var EnumValuesPostingValueType = map[string]PostingValueType{
	"DEFAULT":  PostingValueTypeDEFAULT,
	"BINARY":   PostingValueTypeBINARY,
	"INT":      PostingValueTypeINT,
	"FLOAT":    PostingValueTypeFLOAT,
	"BOOL":     PostingValueTypeBOOL,
	"DATETIME": PostingValueTypeDATETIME,
	"GEO":      PostingValueTypeGEO,
	"UID":      PostingValueTypeUID,
	"PASSWORD": PostingValueTypePASSWORD,
	"STRING":   PostingValueTypeSTRING,
	"OBJECT":   PostingValueTypeOBJECT,
}

func (v PostingValueType) String() string {
	if s, ok := EnumNamesPostingValueType[v]; ok {
		return s
	}
	return "PostingValueType(" + strconv.FormatInt(int64(v), 10) + ")"
}
